# CircleCI configuration file
version: 2.1

jobs: # a basic unit of work in a run
  build_and_test: # your job name
    macos:
      xcode: 14.3.1 # indicate our selected version of Xcode
    environment:
    FL_OUTPUT_DIFR: output
    FASTLANE_LANE: test
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run: bundle install
            - run:
          name: Install Cocoa Pods
          command: pod install --verbose
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE  
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: output
      - store_test_results:
          path: output/scan          
workflows:
  test_build:
    jobs:
      - build_and_test
