# CircleCI configuration file
version: 2.1

jobs: # a basic unit of work in a run
  build-and-test: # your job name
    macos:
      xcode: 14.3.1 # indicate our selected version of Xcode
    environment:
      FL_OUTPUT_DIFR: output
      FASTLANE_LANE: test
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
      - run: bundle install
      - run:
          name: Build and run tests
          command: fastlane scan
      - store_artifacts: # store this build output. Read more: https://circleci.com/docs/2.0/artifacts/
          path: output
      - store_test_results:
          path: output/scan   

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
      
workflows:
  test_build:
    jobs:
      - swiftlint
      - build-and-test
